### PR TITLE
WIP - Adding Conda based minimal notebook(s) for Intel AI-Kit

### PR DESCRIPTION
**Pull request by ashahba**
This PR provides `4` Dockerfiles to build 4 different containers as follows:
```
docker build -f Dockerfile . -t s2i-python-anaconda-base:latest
docker build -f Dockerfile.intel-aikit-modin . -t s2i-python-anaconda-base:intel-aikit-modin
docker build -f Dockerfile.intel-aikit-pt . -t s2i-python-anaconda-base:intel-aikit-pt
docker build -f Dockerfile.intel-aikit-tf . -t s2i-python-anaconda-base:intel-aikit-tf
docker build -f Dockerfile.intel-aikit . -t s2i-python-anaconda-base:intel-aikit
```

As the names describe each container is associated with a specific use-case.

- `s2i-python-anaconda-base:latest` is the base container with `Python 3.7` and `Conda` pre-installed.
- `s2i-python-anaconda-base:intel-aikit-modin` has [intel-aikit-modin](https://anaconda.org/intel/intel-aikit-modin) pre-installed on top of the base container above.
- `s2i-python-anaconda-base:intel-aikit-pt` has [intel-aikit-pytorch](https://anaconda.org/intel/intel-aikit-pytorch) pre-installed on top of the base container above.
- `s2i-python-anaconda-base:intel-aikit-tf` has [intel-aikit-tf](https://anaconda.org/intel/intel-aikit-tensorflow) pre-installed on top of the base container above.
- `s2i-python-anaconda-base:intel-aikit` has all 3 packages [intel-aikit-modin](https://anaconda.org/intel/intel-aikit-tensorflow),  [intel-aikit-pytorch](https://anaconda.org/intel/intel-aikit-pytorch) and [intel-aikit-modin](https://anaconda.org/intel/intel-aikit-tensorflow) pre-installed on top of the base container above.

All non-base containers above, have [Intel Model Zoo](https://github.com/IntelAI/models) cloned on user's work directory.
These containers have been tested to launch properly on a Red Hat open cluster.

A good portion of the code has been borrowed from this repository: https://github.com/jupyter-on-openshift/jupyter-notebooks

### CODE REVIEW

**Comment by ashahba** [comment]
These images are not currently optimized for size and that'll be done during subsequent PR.

**Comment by Xaenalt** [comment]
So, this is somewhat the wrong place for some of this PR. This should be *just* the base python image, whereas the modifications to the other notebook stuff should be in a branch off https://github.com/thoth-station/s2i-minimal-notebook similar to what I did in https://github.com/Xaenalt/s2i-minimal-notebook

**Comment by Xaenalt** [comment]
After some internal discussion, I pulled my code changes into a separate named repo, for now throw the changes into a repo that forks off https://github.com/thoth-station/s2i-minimal-notebook

**Comment by ashahba** [comment]
Thanks @Xaenalt 
I can do that.
Thanks for feedback.

**Comment by ashahba** [comment]
@Xaenalt  So what is this repo for?
https://github.com/red-hat-data-services/s2i-minimal-notebook-anaconda
Should I fork this one and actually make the changes against this repo?
Our notebooks are all Conda based by the way.

**Comment by Xaenalt** [comment]
That one's my fork of the base minimal notebook, but with changes to use Anaconda's package manager instead of pip

You can fork that repo if you prefer, sure

**Comment by ashahba** [comment]
Hi @Xaenalt 
So I created this repo: https://github.com/ashahba/s2i-minimal-notebook/tree/ashahba/s2i-intel-aikit-miniconda

with the changes in this PR, we like to get that into the https://github.com/red-hat-data-services and we can just call it:

https://github.com/red-hat-data-services/s2i-conda-intel-aikit

Would you please help with that?

Thanks.

**Comment by Xaenalt** [comment]
As of right now, we need to have a few internal discussions about the usage of Anaconda (since the image is not intended to be used without Anaconda-CE), I'll get back to you after that

**Pull request closed without merging**
